// <auto-generated />
namespace PixelApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class lastlogindate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(lastlogindate));
        
        string IMigrationMetadata.Id
        {
            get { return "201703011857508_last-login-date"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
